# Generated by Django 4.1.7 on 2023-03-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Telegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.CharField(max_length=25)),
                ('UserFirstName', models.CharField(max_length=200)),
                ('UserLastName', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Telegram',
            },
        ),
    ]
