# Generated by Django 4.1.7 on 2023-03-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backened', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegram',
            name='UserCount',
            field=models.IntegerField(default=1),
        ),
    ]
